const PLAYER_ONE_COLOR = '#CCCC00';
const PLAYER_TWO_COLOR = '#8B0000';
const INNER_BOARD = '#483D8B';
const OUTER_BOARD = '#191970';


export { PLAYER_ONE_COLOR, PLAYER_TWO_COLOR, INNER_BOARD, OUTER_BOARD };
